### ISSUE TITLE
README.md incorrect for requirements.yml entry

### ISSUE THREAD

**Issue by ChrisHindy** [infobloxopen/bloxone-ansible#64]
Currently the README.md provides this example for adding this collection to a project:

```
---
collections:
  - name: git@github.com:infobloxopen/bloxone-ansible.git#ansible_collections/infoblox/b1ddi_modules
    type: git
    version: main
```

This won't work as a SSH key is required.  This example works:

```
---
collections:
  - name: https://github.com/infobloxopen/bloxone-ansible.git#ansible_collections/infoblox/b1ddi_modules
    type: git
    version: main
```
